[package]
name = "hhkbconnstat"
version = "0.1.0"
description = ""
authors = ["progre"]
license = "gpl-3.0"
repository = ""
edition = "2021"
build = "src/build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[build-dependencies]
tauri-build = { version = "1.0.0-beta.4" }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.0.0-beta.8", features = ["api-all", "system-tray"] }
windows = { version = "0.32", features = [
  "Devices_Bluetooth",
  "Devices_Enumeration",
  "Foundation_Collections",
] }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
